apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "incidents-service.fullname" . }}-env
  labels:
    {{- include "incidents-service.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.envVars }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
